project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
    - Schedule.qmd
    - course/index.qmd
    - 00_*
    - 01_*
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for investigating :)"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "Cytometry in R"
  navbar:
    logo: images/hex.svg
    background: white
    left:
      - href: index.qmd
        text: Home
      - text: "Schedule"
        href: Schedule.qmd
      - text: "Course"
        href: course/index.qmd
    right:
    - icon: github
      href: https://github.com/UMGCCCFCSR/CytometryInR
      aria-label: GitHub
  sidebar:
    style: floating
    collapse-level: 1
    contents:
    - section: "Introduction"
      contents:
      - text: "Motivations"
        href: course/00_Motivations/index.qmd
    - section: "Getting Set Up"
      contents:
      - text: "00 - GitHub"
        href: course/00_GitHub/index.qmd
      - text: "00 - Workstation Setup"
        href: course/00_WorkstationSetup/index.qmd
      - text: "00 - Positron"
        href: course/00_Positron/index.qmd
      - text: "00 - Git"
        href: course/00_Git/index.qmd
      - text: "00 - Quarto"
        href: course/00_Quarto/index.qmd
      - text: "00 - Homeworks"
        href: course/00_Homeworks/index.qmd
      - text: "00 - AI"
        href: course/00_AI_Policy/index.qmd
      - text: "00 - Floreada"
        href: course/00_Floreada/index.qmd
    - section: "Intro to R"
      href: course/01_InstallingRPackages/index.qmd
      contents:
      - text: "01 - Installing R Packages"
        href: course/01_InstallingRPackages/index.qmd
      - text: "02 - File Paths"
        href: course/02_FilePaths/index.qmd
      - text: "03 - Inside a .FCS file"
        href: course/03_InsideFCSFile/index.qmd
      - text: "04 - Intro to Tidyverse"
        href: course/04_IntroToTidyverse/index.qmd
      - text: "05 - Gating Sets"
        href: course/05_GatingSets/index.qmd
      - text: "06 - Visualizing With ggplot2"
        href: course/06_Visualizing/index.qmd
      - text: "07 - Transformations and Compensation"
        href: course/07_Transformations/index.qmd
      - text: "08 - Ways to Gate"
        href: course/08_WaysToGate/index.qmd        
      - text: "09 - It's Raining Functions!"
        href: course/09_Functions/index.qmd
    - section: "Cytometry Core"
      href: course/10_Downsampling/index.qmd
      contents:
      - text: "10 - Downsampling and Concatenation"
        href: course/10_Downsampling/index.qmd
      - text: "11 - Data for Statistics"
        href: course/11_DataForStats/index.qmd
      - text: "12 - Spectral Signatures"
        href: course/12_SpectralSignatures/index.qmd
      - text: "13 - Spectral Similarities"
        href: course/13_SpectralSimilarities/index.qmd
      - text: "14 - Unmixing in R"
        href: course/14_Unmixing/index.qmd
      - text: "15 - Data Cleaning"
        href: course/15_DataCleaning/index.qmd
      - text: "16 - Clustering"
        href: course/16_Clustering/index.qmd
      - text: "17 - Normalization"
        href: course/17_Normalization/index.qmd
      - text: "18 - Dimensionality Visualization"
        href: course/18_DimensionalityVisualization/index.qmd
      - text: "19 - Annotation"
        href: course/19_Annotation/index.qmd
    - section: "Beyond the Sandbox"
      href: course/20_GitHubDiving/index.qmd
      contents: 
      - text: "The Art of GitHub Diving"
        href: course/20_GitHubDiving/index.qmd
      - text: "XML files all the way down"
        href: course/21_XMLFiles/index.qmd
      - text: "Utilizing Bioconductor Packages"
        href: course/22_Bioconductor/index.qmd
      - text: "Building your First R package"
        href: course/23_FirstRPackage/index.qmd
      - text: "Reproducibility and Replicability"
        href: course/24_Reproducibility/index.qmd
      - text: "Validating Algorithmic Tools"
        href: course/25_ValidatingAlgorithms/index.qmd
      - text: "Quarto Websites"
        href: course/26_QuartoWebsites/index.qmd
      - text: "Open Source Licenses"
        href: course/27_OpenSource/index.qmd
      - text: "Databases and Repositories"
        href: course/28_Databases/index.qmd
      - text: "Assembling Web Data"
        href: course/29_WebData/index.qmd
    - section: "The World is your Oyster"
      href: course/30_FutureDirections/index.qmd
      contents:         
      - text: "Future Directions"
        href: course/30_FutureDirections/index.qmd
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
   right: |
    ![AGPL-3.0](/images/AGPL3.png)
    ![CC-BY-SA](/images/CCBYSA.png)
format:
  html:
    css: styles.css

